---
- name: Install_CP4I
  hosts: localhost
  vars_files:
    - vars/external_vars.yml
  collections:
    - ibm.cloudcollection
  tasks:
    - name: Create container vpc cluster
      ibm.cloudcollection.ibm_container_vpc_cluster:
        name: "{{ cluster_name }}"
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        flavor: "{{ flavor }}"
        vpc_id: "{{ vpc_id }}"
        zones:
          - subnet_id: "{{ subnet_id }}"
            name: "{{ zone_name }}"
        entitlement: "{{ entitlement }}"
        kube_version: "{{ kube_version }}"
        worker_count: "{{ worker_count }}"
        cos_instance_crn: "{{ cos_instance_crn }}"
